_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True]'
_last_obs:
    value: |-
        OrderedDict([('image', array([[[[ 55,  55,  55, ...,  55,  55,  55],
                 [ 79,  79,  79, ...,  79,  91,  91],
                 [ 67,  55,  55, ...,  67,  87,  55],
                 ...,
                 [131, 131, 123, ..., 119, 111, 119],
                 [123, 123, 123, ..., 119, 119, 119],
                 [123, 119, 119, ..., 119, 119, 111]],

                [[ 55,  55,  55, ...,  55,  55,  55],
                 [ 79,  79,  79, ...,  79,  91,  91],
                 [ 67,  55,  55, ...,  67,  87,  55],
                 ...,
                 [107, 107,  99, ...,  95,  87,  95],
                 [ 99,  99,  99, ...,  95,  95,  95],
                 [ 99,  95,  95, ...,  95,  95,  87]],

                [[ 55,  55,  55, ...,  55,  55,  55],
                 [ 79,  79,  79, ...,  79,  91,  91],
                 [ 67,  55,  55, ...,  67,  87,  55],
                 ...,
                 [ 87,  87,  79, ...,  75,  67,  75],
                 [ 79,  79,  79, ...,  75,  75,  75],
                 [ 79,  75,  75, ...,  75,  75,  67]]]], dtype=uint8)), ('vars', array([[50.]], dtype=float32))])
_last_original_obs:
    value: None
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x737508de7670>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 500000
_vec_normalize_env:
    value: None
_wandb:
    value:
        cli_version: 0.23.1
        e:
            jsrul99gyn0c8nk0iictuy0fcqrxq6rw:
                codePath: src/scenarios/CacodemonRecognition/training_files/basic_example.py
                codePathLocal: basic_example.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1081101176832"
                        used: "45612277760"
                email: 2682261s@student.gla.ac.uk
                executable: /home/battmannwann/Projects/Individual_Project/venv/bin/python
                git:
                    commit: 178db9c3de45aa2b5ca409e322685b7bfe9febe5
                    remote: https://github.com/BattmannWann/The-VizDoom-Experience.git
                gpu: NVIDIA GeForce RTX 3060
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      memoryTotal: "12884901888"
                      name: NVIDIA GeForce RTX 3060
                      uuid: GPU-c4df004e-258c-18a9-a285-5a831eefb36c
                host: DESKTOP-L6DNDAD
                memory:
                    total: "8280821760"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
                program: /home/battmannwann/Projects/Individual_Project/The-VizDoom-Experience/src/scenarios/CacodemonRecognition/training_files/basic_example.py
                python: CPython 3.10.12
                root: /home/battmannwann/Projects/Individual_Project/The-VizDoom-Experience/src/scenarios/CacodemonRecognition/training_files
                startedAt: "2025-12-11T20:40:20.327689Z"
                writerId: jsrul99gyn0c8nk0iictuy0fcqrxq6rw
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 1
                - 3
                - 16
                - 22
            "4": 3.10.12
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
action_noise:
    value: None
action_space:
    value: Discrete(3)
algo:
    value: PPO
batch_size:
    value: 64
clip_range:
    value: FloatSchedule(ConstantSchedule(val=0.2))
clip_range_vf:
    value: None
device:
    value: cuda
ent_coef:
    value: 0.01
env:
    value: <stable_baselines3.common.vec_env.vec_transpose.VecTransposeImage object at 0x73751fee8820>
env_name:
    value: VizdoomCacodemonRecognition-v0
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.0001
lr_schedule:
    value: FloatSchedule(ConstantSchedule(val=0.0003))
max_grad_norm:
    value: 0.5
n_envs:
    value: 1
n_epochs:
    value: 10
n_steps:
    value: 2048
normalize_advantage:
    value: "True"
num_timesteps:
    value: 0
observation_space:
    value: 'Dict(''image'': Box(0, 255, (3, 120, 160), uint8), ''vars'': Box(-inf, inf, (1,), float32))'
policy:
    value: |-
        MultiInputActorCriticPolicy(
          (features_extractor): CombinedExtractor(
            (extractors): ModuleDict(
              (image): NatureCNN(
                (cnn): Sequential(
                  (0): Conv2d(3, 32, kernel_size=(8, 8), stride=(4, 4))
                  (1): ReLU()
                  (2): Conv2d(32, 64, kernel_size=(4, 4), stride=(2, 2))
                  (3): ReLU()
                  (4): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1))
                  (5): ReLU()
                  (6): Flatten(start_dim=1, end_dim=-1)
                )
                (linear): Sequential(
                  (0): Linear(in_features=11264, out_features=256, bias=True)
                  (1): ReLU()
                )
              )
              (vars): Flatten(start_dim=1, end_dim=-1)
            )
          )
          (pi_features_extractor): CombinedExtractor(
            (extractors): ModuleDict(
              (image): NatureCNN(
                (cnn): Sequential(
                  (0): Conv2d(3, 32, kernel_size=(8, 8), stride=(4, 4))
                  (1): ReLU()
                  (2): Conv2d(32, 64, kernel_size=(4, 4), stride=(2, 2))
                  (3): ReLU()
                  (4): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1))
                  (5): ReLU()
                  (6): Flatten(start_dim=1, end_dim=-1)
                )
                (linear): Sequential(
                  (0): Linear(in_features=11264, out_features=256, bias=True)
                  (1): ReLU()
                )
              )
              (vars): Flatten(start_dim=1, end_dim=-1)
            )
          )
          (vf_features_extractor): CombinedExtractor(
            (extractors): ModuleDict(
              (image): NatureCNN(
                (cnn): Sequential(
                  (0): Conv2d(3, 32, kernel_size=(8, 8), stride=(4, 4))
                  (1): ReLU()
                  (2): Conv2d(32, 64, kernel_size=(4, 4), stride=(2, 2))
                  (3): ReLU()
                  (4): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1))
                  (5): ReLU()
                  (6): Flatten(start_dim=1, end_dim=-1)
                )
                (linear): Sequential(
                  (0): Linear(in_features=11264, out_features=256, bias=True)
                  (1): ReLU()
                )
              )
              (vars): Flatten(start_dim=1, end_dim=-1)
            )
          )
          (mlp_extractor): MlpExtractor(
            (policy_net): Sequential(
              (0): Linear(in_features=257, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
            (value_net): Sequential(
              (0): Linear(in_features=257, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
          )
          (action_net): Linear(in_features=64, out_features=3, bias=True)
          (value_net): Linear(in_features=64, out_features=1, bias=True)
        )
policy_class:
    value: <class 'stable_baselines3.common.policies.MultiInputActorCriticPolicy'>
policy_kwargs:
    value: '{}'
rollout_buffer:
    value: <stable_baselines3.common.buffers.DictRolloutBuffer object at 0x73751b141600>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.DictRolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
sde_sample_freq:
    value: -1
seed:
    value: None
start_time:
    value: 1765485623105744383
target_kl:
    value: None
tensorboard_log:
    value: None
total_timesteps:
    value: 500000
use_sde:
    value: "False"
verbose:
    value: 2
vf_coef:
    value: 0.5
